### ISSUE TITLE
License?  MIT please?

### ISSUE THREAD

**Issue by vsivsi** [bhoriuchi/rethinkdown#1]
Hi, this looks like an interesting project, thanks for writing/sharing it. I was just about to write the equivalent myself, but I thought I'd search around again one more time before beginning my coding.

I'd love to try it out, but will need an acceptable LICENSE file before I can actually do so.

Thanks!

**Comment by bhoriuchi** [comment]
Added. Let me know if you need it included in the npm package and I will publish a version with it

**Comment by vsivsi** [comment]
Great! And thanks for the super quick response. Looks like the published npm package is already tagged as MIT, so good to go, no need to do an unnecessary publish just to push this file. I'm sure I'll have some more suggestions/fixes for you as I dig into the code a bit and try things out!

**Comment by bhoriuchi** [comment]
@vsivsi I actually added a new feature today and published `0.3.0`. There is now a `singleTable` option that allows you to put multiple locations into a single table. This is accomplished by adding location as a field in each document and filtering during get/put/del/batch operations.

I look forward to suggestions
